language: python
python: 3.5

install:
- python setup.py build install

script:
- python setup.py test

deploy:
  provider: pypi
  user: isivisi
  distributions: sdist
  skip_cleanup: true
  password:
    secure: k03495XFq7E73dBHrAVgt6j3gRZJ1i68n76Ff3c1nK9uIhDMWLUF3tJ7gIibMimwd9LXOYMCcFDe28FQX7zxx27LBZ4E9+/7G0vgaoRKgSY1nodAP3Gr3z47Y1CJm/dicZi2mdHFUXklEVvYK52mQm7Rq5GUvkzK3xaTDPub7FmXMOt28jHmh0ytXwkIxe5K2H3Wude5ezt1kgH/tlTNfHQ+oAQKr5U/CbYeyfiHNDGD+0uA3IMR04UVRCBRsgbfAwhfQbsV2freczU0lhFnQiA7WqLBYycbfzLQJH3Ni5spg6rPcjkJsqpWOcP1C1hghg6FTuulEdQHtX/XEshTanzF7cJxVCY91Afktymuj3F8CVW6hZsSuEbaZm/6fKx1J5DI9YN6l5NiLAaAlSwRQGQtRj6z5yocbsExAaIaGeaNupwLi8bWnXO3fNj82MB+AQCHQ3ZVhF3s5baX3SpXQz9FBDiSdnfC8AUYIndnH16bEBnkBD/5vtgLrU80eFvt6g5Yp/HtX7HzdG1DKonWandyjLJWHYGAJ3U/70FY10AUNzcKcLszbvWE5lzyNBqcLyEU8k6J7P4GYycQwEvkX5L5zO9aTKw69aoTjdpKExuD7saoQRGSirb3sWoFwfCpU4xURIZnPH+x/StIE6Ee7w+XcpjhHm/rzibn3Pa+otg=
  on:
    branch: master
    tags: true